apiVersion: v1
kind: Service
metadata:
  name: {{ include "stipend.fullname" . }}
  labels:
    {{- include "stipend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stipend.selectorLabels" . | nindent 4 }}
---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stipend.serviceAccountName" . }}
  labels:
    {{- include "stipend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# Stipend never calls the Kubernetes API.
automountServiceAccountToken: false
{{- end }}
---
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stipend.fullname" . }}
  labels:
    {{- include "stipend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "stipend.selectorLabels" . | nindent 6 }}
{{- end }}
